FROM golang:1.20-bullseye as builder

WORKDIR /src
COPY . .
RUN go mod tidy -v \
    && go build -o build/dvt_service main.go

FROM node:16.20.2-bullseye as builder2

WORKDIR /src

COPY ./makeShares .

RUN yarn \
    && yarn global add typescript \
    && yarn global add pkg \
    && tsc&&pkg dist/makeShares.js -t node16-linux-x64 -o makeShares --compress GZip

FROM debian:bullseye as prod

WORKDIR /root

COPY --from=builder /src/build/dvt_service .
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder2 /src/makeShares .

ENV GIN_MODE release

EXPOSE 3000

CMD ["/root/dvt_service","c"]